version: '3.3'
services:
    docstore-web:
        restart: always
        image: swiftlatex/docstore
        container_name: docstore
        depends_on:
            - mongo_server
        ports:
            - 80:5000
        environment:
            MONGODB_URL: mongodb://mongo_server:27017/docstore
            ACCESS_KEY: eca4da50d2a16asd448805b452ccaea7
            HMAC_KEY: eca17a50d2adseadd448805b452ccae12
    mongo_server:
      restart: always
      image: mongo
      container_name: mongo_server
      expose:
      - 27017
      volumes:
      - ~/mongo_data:/data/db

